import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <nav style={{ 
          width: "100%",
          backgroundColor: "teal",
          fontSize: "30px", 
          display: "flex", 
          justifyContent: "space-evenly", 
          }}>

          <Link href="/"  style={{borderLeft: "1px solid black", borderRight: "1px solid black"}}>Home</Link>
          <Link href="../articles" style={{borderLeft: "1px solid black", borderRight: "1px solid black"}}>Articles</Link>
          <Link href="../posts" style={{borderLeft: "1px solid black", borderRight: "1px solid black"}}>Posts</Link>
        </nav>
        {children}
        </body>
    </html>
  )
}
